---
- name: Install linux audit subsystem
  tags: ['auditd']
  package:
    name: "{{ audit_packages }}"
    state: present
  notify:
    - restart auditd

- name: Install auditd configurations
  tags: ['auditd']
  package:
  loop:
    - audit/auditd.conf
    - audisp/audispd.conf
    - audisp/audisp-remote.conf
    - audisp/plugins.d/au-remote.conf
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: '640'
    owner: root
    group: root
  notify:
    - restart auditd

- name: Install audit rules
  tags: ['auditd']
  package:
  loop: "{{ audit_rules }}"
  copy:
    content: "{{ item.rules | join('\n') }}\n"
    dest: "{{ audit_rules_dir }}/{{ item.name }}.rules"
    mode: '640'
    owner: root
    group: root
  notify:
    - restart auditd
