---
- name: Install linux audit subsystem
  package:
    name: "{{ audit_packages }}"
    state: present
  notify:
    - restart auditd

- name: Install auditd configurations
  loop:
    - audit/auditd.conf
    - audispd/audispd.conf
    - audispd/audisp-remote.conf
    - audispd/plugins.d/au-remote.conf
  template:
    src: "templates/{{ item }}"
    dest: "/etc/{{ item }}"
    mode: '640'
    owner: root
    group: root
  notify:
    - restart auditd

- name: Install audit rules
  loop: "{{ audit_rules }}"
  copy:
    content: "{{ item.rules | join('\n') }}\n"
    dest: "{{ audit_rules_dir }}/{{ item.name }}.rules"
    mode: '640'
    owner: root
    group: root
  notify:
    - restart auditd
